/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jonrss (https://sketchfab.com/huy14320000006)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ducati-v4r-76701e23fbcb408dae5c892594199a52
Title: Ducati v4r
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Ducati V4R.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01} position={[0, -17, 0]}>
        <group
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r14_V���t_Li���u007_0"].geometry}
            material={materials["Vt_Liu.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r14_V���t_Li���u011_0"].geometry}
            material={materials["Vt_Liu.011"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r14_V���t_Li���u019_0"].geometry}
            material={materials["Vt_Liu.019"]}
          />
        </group>
        <group
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r19_V���t_Li���u002_0"].geometry}
            material={materials["Vt_Liu.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r19_V���t_Li���u026_0"].geometry}
            material={materials["Vt_Liu.026"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r19_V���t_Li���u003_0"].geometry}
            material={materials["Vt_Liu.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r19_V���t_Li���u027_0"].geometry}
            material={materials["Vt_Liu.027"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r19_V���t_Li���u010_0"].geometry}
            material={materials["Vt_Liu.010"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r19_V���t_Li���u030_0"].geometry}
            material={materials["Vt_Liu.030"]}
          />
        </group>
        <group
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r10_V���t_Li���u002_0"].geometry}
            material={materials["Vt_Liu.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r10_V���t_Li���u_0"].geometry}
            material={materials.Vt_Liu}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r10_V���t_Li���u007_0"].geometry}
            material={materials["Vt_Liu.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r10_V���t_Li���u001_0"].geometry}
            material={materials["Vt_Liu.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r10_V���t_Li���u006_0"].geometry}
            material={materials["Vt_Liu.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r10_V���t_Li���u005_0"].geometry}
            material={materials["Vt_Liu.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["v4r10_V���t_Li���u003_0"].geometry}
            material={materials["Vt_Liu.003"]}
          />
        </group>
        <group
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["V4r1_V���t_Li���u025_0"].geometry}
            material={materials["Vt_Liu.025"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["V4r1_V���t_Li���u024_0"].geometry}
            material={materials["Vt_Liu.024"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["V4r1_V���t_Li���u027_0"].geometry}
            material={materials["Vt_Liu.027"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["V4r1_V���t_Li���u023_0"].geometry}
            material={materials["Vt_Liu.023"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["V4r1_V���t_Li���u026_0"].geometry}
            material={materials["Vt_Liu.026"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["V4r1_V���t_Li���u002_0"].geometry}
            material={materials["Vt_Liu.002"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r7_V���t_Li���u011_0"].geometry}
          material={materials["Vt_Liu.011"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r6_V���t_Li���u_0"].geometry}
          material={materials.Vt_Liu}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r8_V���t_Li���u014_0"].geometry}
          material={materials["Vt_Liu.014"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r9_V���t_Li���u007_0"].geometry}
          material={materials["Vt_Liu.007"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r11_V���t_Li���u013_0"].geometry}
          material={materials["Vt_Liu.013"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r17_V���t_Li���u012_0"].geometry}
          material={materials["Vt_Liu.012"]}
          position={[-2627.599, 878.572, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r16_V���t_Li���u012_0"].geometry}
          material={materials["Vt_Liu.012"]}
          position={[2687.718, 999.322, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r2_V���t_Li���u007_0"].geometry}
          material={materials["Vt_Liu.007"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r4_V���t_Li���u008_0"].geometry}
          material={materials["Vt_Liu.008"]}
          position={[2687.718, 999.322, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r3_V���t_Li���u007_0"].geometry}
          material={materials["Vt_Liu.007"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r20_V���t_Li���u008_0"].geometry}
          material={materials["Vt_Liu.008"]}
          position={[-2627.599, 878.572, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r5_V���t_Li���u010_0"].geometry}
          material={materials["Vt_Liu.010"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r13_V���t_Li���u009_0"].geometry}
          material={materials["Vt_Liu.009"]}
          position={[2687.718, 999.322, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r12_V���t_Li���u009_0"].geometry}
          material={materials["Vt_Liu.009"]}
          position={[-2627.599, 878.572, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r18_V���t_Li���u020_0"].geometry}
          material={materials["Vt_Liu.020"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["v4r15_V���t_Li���u020_0"].geometry}
          material={materials["Vt_Liu.020"]}
          position={[-20.161, -211.721, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-36.215, 36.215, 36.215]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Ducati V4R.glb");
